<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WebApi.Interface\WebApi.Interface.csproj" />
    <ProjectReference Include="..\..\WebApi.Models\WebApi.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
  <None Include="..\..\Scripts\reglas-preliminares-completas.json">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <Link>Scripts\reglas-preliminares-completas.json</Link>
  </None>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
